### PR TITLE
Docs fix spellig issues

### PR DESCRIPTION
**Pull request by nnsW3**
Hello
I found and fixed several spelling issues.
Hope it helps.
Br, Elias.

### CODE REVIEW

**Comment by EngrPips** [comment]
Hello @nnsW3, Thanks for the contribution. This will be addressed appropriately as soon as possible.

**Comment by nnsW3** [comment]
Glad I could help

**Comment by EngrPips** [comment]
Indeed

**Comment by cromewar** [comment]
That's amazing @nnsW3, thanks for the contribution!

**Pull request merged**
